language: node_js
os:
- linux
node_js:
- 10
cache:
  yarn: true
env:
  matrix:
  - YARN_GPG=no
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
before_deploy:
  - yarn version --patch
deploy:
  provider: npm
  email: alexshe@wix.com
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master
