language: node_js

os:
  - linux

node_js:
  - 12

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH=$HOME/.yarn/bin:$PATH

deploy:
  provider: npm
  edge: true
  email: alexshe@wix.com
  api-token: "$NPM_TOKEN"
  on:
    branch: master
